import { OffPlanProject, Property, Recommendation, User } from "@/types";

// Real Unsplash real-estate photographs. These are the verified IDs that
// render in-browser; `unoptimized` images (see next.config.js) load them
// directly so they don't depend on the Next image optimizer. Each property
// gets 5 photos and a globally-unique hero (the stride of 5 over 14 photos is
// coprime, so images[0] never repeats across properties).
const PROPERTY_PHOTOS = [
  "1600596542815-ffad4c1539a9",
  "1600607687939-ce8a6c25118c",
  "1600585154340-be6161a56a0c",
  "1502672260266-1c1ef2d93688",
  "1560448204-e02f11c3d0e2",
  "1600047509807-ba8f99d2cdde",
  "1494526585095-c41746248156",
  "1505693416388-ac5ce068fe85",
  "1564013799919-ab600027ffc6",
  "1600585154526-990dced4db0d",
  "1502672023488-70e25813eb80",
  "1511818966892-d7d671e672a2",
  "1512918728675-ed5a9ecdebfd",
  "1524230572899-a752b3835840",
];

function unsplash(id: string): string {
  return `https://images.unsplash.com/photo-${id}?w=900&q=80&auto=format&fit=crop`;
}

function propertyImages(seed: number): string[] {
  const base = (seed - 1) * 5;
  return Array.from({ length: 5 }, (_, k) =>
    unsplash(PROPERTY_PHOTOS[(base + k) % PROPERTY_PHOTOS.length])
  );
}

export const mockUser: User = {
  id: "u1",
  email: "alex@example.com",
  firstName: "Alex",
  lastName: "Rivera",
  role: "buyer",
  avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100",
  createdAt: "2025-01-15",
};

export const mockProperties: Property[] = [
  {
    id: "p1",
    title: "Modern Craftsman with Mountain Views",
    description:
      "Stunning 4-bedroom home featuring an open floor plan, chef's kitchen with quartz countertops, and a spacious backyard perfect for entertaining.",
    price: 875000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2850,
    propertyType: "house",
    listingType: "sale",
    address: {
      street: "1247 Pine Ridge Dr",
      city: "Denver",
      state: "CO",
      zipCode: "80202",
      country: "US",
      lat: 39.7392,
      lng: -104.9903,
    },
    images: propertyImages(1),
    amenities: ["Garage", "Pool", "Smart Home", "Fireplace", "Garden"],
    yearBuilt: 2018,
    lotSize: 0.25,
    status: "active",
    aiPriceEstimate: 862000,
    appreciationForecast: {
      year1: 4.2,
      year3: 12.8,
      year5: 22.5,
      year10: 48.3,
      confidence: 87,
    },
    imageTags: [
      { label: "Modern Kitchen", confidence: 0.94, category: "room" },
      { label: "Hardwood Floors", confidence: 0.89, category: "feature" },
      { label: "Excellent Condition", confidence: 0.91, category: "condition" },
    ],
    createdAt: "2025-05-01",
    updatedAt: "2025-06-01",
  },
  {
    id: "p2",
    title: "Downtown Luxury Condo",
    description:
      "Premium 2-bedroom condo in the heart of downtown with floor-to-ceiling windows, rooftop access, and concierge service.",
    price: 425000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1200,
    propertyType: "condo",
    listingType: "sale",
    address: {
      street: "890 Market St #2401",
      city: "San Francisco",
      state: "CA",
      zipCode: "94102",
      country: "US",
      lat: 37.7749,
      lng: -122.4194,
    },
    images: propertyImages(2),
    amenities: ["Concierge", "Gym", "Rooftop", "Parking"],
    yearBuilt: 2020,
    status: "active",
    aiPriceEstimate: 438000,
    appreciationForecast: {
      year1: 3.1,
      year3: 9.5,
      year5: 16.2,
      year10: 35.0,
      confidence: 82,
    },
    createdAt: "2025-05-10",
    updatedAt: "2025-06-01",
  },
  {
    id: "p3",
    title: "Charming Family Townhouse",
    description:
      "Beautiful 3-bed townhouse in top-rated school district. Walk to parks, cafes, and public transit.",
    price: 3200,
    bedrooms: 3,
    bathrooms: 2.5,
    sqft: 1800,
    propertyType: "townhouse",
    listingType: "rent",
    address: {
      street: "456 Oak Valley Ln",
      city: "Austin",
      state: "TX",
      zipCode: "78701",
      country: "US",
      lat: 30.2672,
      lng: -97.7431,
    },
    images: propertyImages(3),
    amenities: ["Patio", "In-Unit Laundry", "Pet Friendly"],
    yearBuilt: 2015,
    status: "active",
    createdAt: "2025-05-20",
    updatedAt: "2025-06-01",
  },
  {
    id: "p4",
    title: "Skyline Penthouse in Midtown",
    description:
      "Luxury penthouse with wraparound terrace, skyline views, and concierge-led living in one of the city's most connected districts.",
    price: 1245000,
    bedrooms: 3,
    bathrooms: 3.5,
    sqft: 2420,
    currency: "USD",
    propertyType: "condo",
    listingType: "sale",
    address: {
      street: "22 Mercer Street, PH 18",
      city: "New York",
      state: "NY",
      zipCode: "10012",
      country: "US",
      lat: 40.7128,
      lng: -74.006,
    },
    images: propertyImages(4),
    amenities: ["Terrace", "Concierge", "Gym", "Doorman", "Wine Cellar"],
    yearBuilt: 2021,
    status: "active",
    aiPriceEstimate: 1288000,
    appreciationForecast: {
      year1: 2.9,
      year3: 9.1,
      year5: 15.4,
      year10: 31.8,
      confidence: 84,
    },
    createdAt: "2025-05-25",
    updatedAt: "2025-06-01",
  },
  {
    id: "p5",
    title: "Garden Villa in Whitefield",
    description:
      "Contemporary villa with private garden, work-from-home studio, and calm family-focused planning for fast-growing city buyers.",
    price: 18500000,
    bedrooms: 4,
    bathrooms: 4,
    sqft: 3280,
    currency: "INR",
    propertyType: "house",
    listingType: "sale",
    address: {
      street: "18 Orchid Avenue",
      city: "Bengaluru",
      state: "Karnataka",
      zipCode: "560066",
      country: "IN",
      lat: 12.9716,
      lng: 77.5946,
    },
    images: propertyImages(5),
    amenities: ["Private Garden", "Study", "Covered Parking", "Solar Ready"],
    yearBuilt: 2019,
    status: "active",
    aiPriceEstimate: 17850000,
    appreciationForecast: {
      year1: 6.5,
      year3: 18.2,
      year5: 32.7,
      year10: 61.4,
      confidence: 81,
    },
    createdAt: "2025-05-28",
    updatedAt: "2025-06-01",
  },
  {
    id: "p6",
    title: "Waterfront Loft on the Harbour",
    description:
      "Bright loft with lake views, curated finishes, and a highly walkable location near dining and transit.",
    price: 935000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1380,
    currency: "CAD",
    propertyType: "apartment",
    listingType: "sale",
    address: {
      street: "88 Queens Quay W #1207",
      city: "Toronto",
      state: "ON",
      zipCode: "M5J 0B6",
      country: "CA",
      lat: 43.6532,
      lng: -79.3832,
    },
    images: propertyImages(6),
    amenities: ["Lake View", "Walkable", "Concierge", "Parking"],
    yearBuilt: 2017,
    status: "active",
    aiPriceEstimate: 948000,
    appreciationForecast: {
      year1: 3.4,
      year3: 10.4,
      year5: 18.9,
      year10: 39.2,
      confidence: 83,
    },
    createdAt: "2025-05-30",
    updatedAt: "2025-06-01",
  },
  {
    id: "p7",
    title: "Executive Lease in Central Gurgaon",
    description:
      "Premium rental apartment with amenity deck, efficient commute access, and corporate-ready interiors.",
    price: 92000,
    bedrooms: 3,
    bathrooms: 3,
    sqft: 1960,
    currency: "INR",
    propertyType: "apartment",
    listingType: "rent",
    address: {
      street: "120 Golf Course Road",
      city: "Gurugram",
      state: "Haryana",
      zipCode: "122002",
      country: "IN",
      lat: 28.4595,
      lng: 77.0266,
    },
    images: propertyImages(7),
    amenities: ["Gym", "Pool", "Coworking", "Security"],
    yearBuilt: 2022,
    status: "active",
    createdAt: "2025-06-02",
    updatedAt: "2025-06-02",
  },
  {
    id: "p8",
    title: "Heritage Brownstone Near Kensington",
    description:
      "Elegant historic home with modernized interiors, landscaped garden, and strong school access.",
    price: 1495000,
    bedrooms: 5,
    bathrooms: 4,
    sqft: 3125,
    currency: "GBP",
    propertyType: "house",
    listingType: "sale",
    address: {
      street: "14 Clarendon Road",
      city: "London",
      state: "Greater London",
      zipCode: "W11 4SJ",
      country: "GB",
      lat: 51.5072,
      lng: -0.1276,
    },
    images: propertyImages(8),
    amenities: ["Garden", "Fireplace", "Period Details", "Study"],
    yearBuilt: 1935,
    status: "active",
    aiPriceEstimate: 1521000,
    appreciationForecast: {
      year1: 2.4,
      year3: 6.9,
      year5: 12.8,
      year10: 25.1,
      confidence: 79,
    },
    createdAt: "2025-06-01",
    updatedAt: "2025-06-01",
  },
  {
    id: "p9",
    title: "Dubai Marina View Residence",
    description:
      "High-floor apartment with marina views, premium amenities, and flexible ownership appeal for international investors.",
    price: 2150000,
    bedrooms: 2,
    bathrooms: 2.5,
    sqft: 1490,
    currency: "AED",
    propertyType: "condo",
    listingType: "sale",
    address: {
      street: "Marina Promenade Tower",
      city: "Dubai",
      state: "Dubai",
      zipCode: "00000",
      country: "AE",
      lat: 25.2048,
      lng: 55.2708,
    },
    images: propertyImages(9),
    amenities: ["Marina View", "Pool", "Gym", "Security"],
    yearBuilt: 2021,
    status: "active",
    aiPriceEstimate: 2190000,
    appreciationForecast: {
      year1: 4.8,
      year3: 13.6,
      year5: 24.4,
      year10: 44.5,
      confidence: 77,
    },
    createdAt: "2025-06-02",
    updatedAt: "2025-06-02",
  },
  {
    id: "p10",
    title: "Investor Duplex Near the Bay",
    description:
      "A rare duplex with two living zones, strong rental yield profile, and easy access to transit and dining.",
    price: 1025000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2680,
    currency: "CAD",
    propertyType: "townhouse",
    listingType: "sale",
    address: {
      street: "512 Bayside Crescent",
      city: "Vancouver",
      state: "BC",
      zipCode: "V5K 0A1",
      country: "CA",
      lat: 49.2827,
      lng: -123.1207,
    },
    images: propertyImages(10),
    amenities: ["Duplex", "Transit Access", "Rental Friendly", "Deck"],
    yearBuilt: 2016,
    status: "pending",
    aiPriceEstimate: 996000,
    appreciationForecast: {
      year1: 3.8,
      year3: 11.5,
      year5: 20.7,
      year10: 38.6,
      confidence: 80,
    },
    createdAt: "2025-06-03",
    updatedAt: "2025-06-03",
  },
];

export const mockProjects: OffPlanProject[] = [
  {
    id: "op1",
    name: "Marina Skyline Residences",
    developer: "Emaar Properties",
    city: "Dubai",
    state: "Dubai",
    country: "AE",
    status: "selling",
    completion: "Q4 2027",
    priceFrom: 1850000,
    currency: "AED",
    downPaymentPct: 20,
    duringConstructionPct: 40,
    handoverPct: 40,
    paymentPlanLabel: "60 / 40",
    rentalYield: 7.2,
    appreciation5yr: 31.5,
    unitTypes: [
      { type: "Studio", sizeSqft: 480, priceFrom: 1850000, available: 12 },
      { type: "1 Bedroom", sizeSqft: 760, priceFrom: 2450000, available: 28 },
      { type: "2 Bedroom", sizeSqft: 1180, priceFrom: 3680000, available: 16 },
      { type: "3 Bedroom", sizeSqft: 1720, priceFrom: 5950000, available: 6 },
    ],
    amenities: ["Infinity Pool", "Marina View", "Smart Home", "Concierge", "Gym", "Beach Access"],
    images: propertyImages(9),
    description:
      "A waterfront landmark with floor-to-ceiling glass, private marina access, and a 60/40 payment plan ideal for international investors seeking strong rental yields.",
    location: { lat: 25.0805, lng: 55.1403, nearby: ["Dubai Marina Mall", "Metro (5 min)", "JBR Beach", "Sheikh Zayed Rd"] },
  },
  {
    id: "op2",
    name: "Downtown Vista Towers",
    developer: "DAMAC",
    city: "Dubai",
    state: "Dubai",
    country: "AE",
    status: "under-construction",
    completion: "Q2 2026",
    priceFrom: 1320000,
    currency: "AED",
    downPaymentPct: 10,
    duringConstructionPct: 50,
    handoverPct: 40,
    paymentPlanLabel: "60 / 40",
    rentalYield: 6.5,
    appreciation5yr: 27.8,
    unitTypes: [
      { type: "1 Bedroom", sizeSqft: 690, priceFrom: 1320000, available: 34 },
      { type: "2 Bedroom", sizeSqft: 1050, priceFrom: 2180000, available: 22 },
      { type: "3 Bedroom", sizeSqft: 1560, priceFrom: 3420000, available: 9 },
    ],
    amenities: ["Burj Khalifa View", "Sky Lounge", "Co-working", "Pool", "Kids Play", "EV Charging"],
    images: propertyImages(4),
    description:
      "Steps from the city's cultural core, Downtown Vista pairs a low 10% down payment with a post-handover plan and best-in-class amenities.",
    location: { lat: 25.1972, lng: 55.2744, nearby: ["Dubai Mall", "Burj Khalifa", "Opera District", "Metro (3 min)"] },
  },
  {
    id: "op3",
    name: "Whitefield Greens",
    developer: "Prestige Group",
    city: "Bengaluru",
    state: "Karnataka",
    country: "IN",
    status: "pre-launch",
    completion: "Q1 2028",
    priceFrom: 12500000,
    currency: "INR",
    downPaymentPct: 15,
    duringConstructionPct: 65,
    handoverPct: 20,
    paymentPlanLabel: "80 / 20",
    rentalYield: 4.1,
    appreciation5yr: 38.2,
    unitTypes: [
      { type: "2 BHK", sizeSqft: 1180, priceFrom: 12500000, available: 40 },
      { type: "3 BHK", sizeSqft: 1640, priceFrom: 17800000, available: 24 },
      { type: "4 BHK", sizeSqft: 2280, priceFrom: 24500000, available: 8 },
    ],
    amenities: ["Clubhouse", "IT-Park Proximity", "Solar Ready", "Jogging Track", "Pool", "Yoga Deck"],
    images: propertyImages(5),
    description:
      "A pre-launch tech-corridor community with a construction-linked plan, strong appreciation outlook, and family-first master planning.",
    location: { lat: 12.9698, lng: 77.7499, nearby: ["ITPL", "Phoenix Marketcity", "Metro (Purple Line)", "Intl. Schools"] },
  },
  {
    id: "op4",
    name: "Palm Crescent Villas",
    developer: "Nakheel",
    city: "Dubai",
    state: "Dubai",
    country: "AE",
    status: "selling",
    completion: "Q3 2027",
    priceFrom: 9200000,
    currency: "AED",
    downPaymentPct: 25,
    duringConstructionPct: 35,
    handoverPct: 40,
    paymentPlanLabel: "60 / 40",
    rentalYield: 5.8,
    appreciation5yr: 29.4,
    unitTypes: [
      { type: "4 BR Villa", sizeSqft: 4200, priceFrom: 9200000, available: 7 },
      { type: "5 BR Villa", sizeSqft: 5600, priceFrom: 13800000, available: 4 },
    ],
    amenities: ["Private Beach", "Private Pool", "Smart Villa", "Maid's Room", "2-Car Garage", "Sea View"],
    images: propertyImages(1),
    description:
      "Limited-release waterfront villas on the Palm with private beach frontage and a flexible handover-weighted payment structure.",
    location: { lat: 25.1124, lng: 55.139, nearby: ["The Pointe", "Atlantis", "Nakheel Mall", "Marina (10 min)"] },
  },
  {
    id: "op5",
    name: "Creek Harbour Lofts",
    developer: "Emaar Properties",
    city: "Dubai",
    state: "Dubai",
    country: "AE",
    status: "ready",
    completion: "Ready to move",
    priceFrom: 1680000,
    currency: "AED",
    downPaymentPct: 30,
    duringConstructionPct: 0,
    handoverPct: 70,
    paymentPlanLabel: "Ready",
    rentalYield: 7.8,
    appreciation5yr: 24.1,
    unitTypes: [
      { type: "1 Bedroom", sizeSqft: 720, priceFrom: 1680000, available: 11 },
      { type: "2 Bedroom", sizeSqft: 1120, priceFrom: 2540000, available: 8 },
    ],
    amenities: ["Creek View", "Ready Now", "Retail Podium", "Pool", "Gym", "Marina Berths"],
    images: propertyImages(6),
    description:
      "Move-in-ready waterfront lofts at Dubai Creek Harbour with the highest rental yield in the portfolio and immediate income potential.",
    location: { lat: 25.1985, lng: 55.353, nearby: ["Creek Marina", "Ras Al Khor Sanctuary", "Downtown (12 min)", "DXB Airport (15 min)"] },
  },
];

export const mockRecommendations: Recommendation[] = mockProperties.map(
  (property, i) => ({
    propertyId: property.id,
    property,
    matchScore: [96, 93, 90, 89, 88, 86, 84, 83, 81, 79][i],
    confidence: [92, 89, 88, 87, 86, 84, 83, 81, 80, 78][i],
    rank: i + 1,
    reasons: [
      {
        factor: "Budget Fit",
        weight: 0.28,
        description: "Within your $900K budget with room to negotiate",
        sentiment: "positive",
      },
      {
        factor: "School District",
        weight: 0.22,
        description: "Rated 9/10 — matches your priority for top schools",
        sentiment: "positive",
      },
      {
        factor: "Commute",
        weight: 0.18,
        description: "22 min to downtown — under your 30 min limit",
        sentiment: "positive",
      },
      {
        factor: "Lifestyle",
        weight: 0.15,
        description: "Backyard & garage match your outdoor lifestyle quiz",
        sentiment: "positive",
      },
    ],
  })
);
