/**
 * Dependency-free PDF generation.
 *
 * Produces real, valid PDF files entirely in the browser using the built-in
 * Helvetica fonts (no embedding, no external library). The generated bytes are
 * wrapped in a Blob and downloaded via a temporary anchor, so clicking a button
 * saves a proper `.pdf` file — no pop-ups, no print dialog, works offline.
 */

import { siteConfig } from "@/config/site";

type RGB = [number, number, number];

const WHITE: RGB = [1, 1, 1];
const INK: RGB = [0.06, 0.09, 0.16]; // #0f172a
const DARK: RGB = [0.2, 0.25, 0.33]; // #334155
const GRAY: RGB = [0.39, 0.45, 0.55]; // #64748b
const BORDER: RGB = [0.886, 0.91, 0.94]; // #e2e8f0

// Brand gradient stops (#2f6bff → #7c3aed → #10b6a0)
const STOPS: RGB[] = [
  [0.184, 0.42, 1.0],
  [0.486, 0.227, 0.929],
  [0.063, 0.714, 0.627],
];

const fmt = (n: number) => Number(n).toFixed(2);

function sanitize(s: string): string {
  return (s ?? "")
    .normalize("NFKD")
    .replace(/[—–]/g, "-")
    .replace(/[“”]/g, '"')
    .replace(/[‘’]/g, "'")
    .replace(/[^\x20-\x7E]/g, "");
}

function esc(s: string): string {
  return sanitize(s)
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");
}

// Rough Helvetica advance width (good enough for wrapping / right-alignment).
const textWidth = (s: string, size: number) => sanitize(s).length * size * 0.5;

function lerp(a: RGB, b: RGB, t: number): RGB {
  return [a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t, a[2] + (b[2] - a[2]) * t];
}

function gradColor(t: number): RGB {
  return t < 0.5 ? lerp(STOPS[0], STOPS[1], t / 0.5) : lerp(STOPS[1], STOPS[2], (t - 0.5) / 0.5);
}

function wrap(text: string, size: number, maxWidth: number): string[] {
  const words = sanitize(text).split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    const test = line ? `${line} ${word}` : word;
    if (textWidth(test, size) > maxWidth && line) {
      lines.push(line);
      line = word;
    } else {
      line = test;
    }
  }
  if (line) lines.push(line);
  return lines.length ? lines : [""];
}

class Pdf {
  readonly W = 595.28;
  readonly H = 841.89;
  readonly margin = 48;
  readonly contentW = 595.28 - 96;

  private pages: string[] = [];
  private cur = "";
  y = 0;

  constructor() {
    this.y = this.H - this.margin;
  }

  // --- low-level drawing ----------------------------------------------------
  private op(s: string) {
    this.cur += s;
  }

  fillRect(x: number, y: number, w: number, h: number, c: RGB) {
    this.op(`${fmt(c[0])} ${fmt(c[1])} ${fmt(c[2])} rg\n${fmt(x)} ${fmt(y)} ${fmt(w)} ${fmt(h)} re\nf\n`);
  }

  strokeRect(x: number, y: number, w: number, h: number, c: RGB, lw = 0.75) {
    this.op(
      `${fmt(lw)} w\n${fmt(c[0])} ${fmt(c[1])} ${fmt(c[2])} RG\n${fmt(x)} ${fmt(y)} ${fmt(w)} ${fmt(h)} re\nS\n`
    );
  }

  line(x1: number, y1: number, x2: number, y2: number, c: RGB, lw = 0.5) {
    this.op(
      `${fmt(lw)} w\n${fmt(c[0])} ${fmt(c[1])} ${fmt(c[2])} RG\n${fmt(x1)} ${fmt(y1)} m ${fmt(x2)} ${fmt(y2)} l S\n`
    );
  }

  /** Draw text with its baseline at (x, baselineY). */
  text(x: number, baselineY: number, size: number, bold: boolean, c: RGB, str: string) {
    this.op(
      `BT\n/${bold ? "F2" : "F1"} ${fmt(size)} Tf\n${fmt(c[0])} ${fmt(c[1])} ${fmt(c[2])} rg\n` +
        `1 0 0 1 ${fmt(x)} ${fmt(baselineY)} Tm\n(${esc(str)}) Tj\nET\n`
    );
  }

  gradientBand(x: number, y: number, w: number, h: number) {
    const N = 48;
    const sliceW = w / N;
    for (let i = 0; i < N; i++) {
      this.fillRect(x + i * sliceW, y, sliceW + 0.6, h, gradColor(i / (N - 1)));
    }
  }

  // --- flow helpers (y = top of next content, in PDF coords) ----------------
  private ensure(h: number) {
    if (this.y - h < this.margin + 28) this.newPage();
  }

  newPage() {
    this.pages.push(this.cur);
    this.cur = "";
    this.y = this.H - this.margin;
  }

  heading(s: string) {
    this.ensure(28);
    this.text(this.margin, this.y - 13, 11, true, GRAY, s.toUpperCase());
    this.y -= 26;
  }

  paragraph(s: string, size = 11, color: RGB = DARK) {
    for (const ln of wrap(s, size, this.contentW)) {
      this.ensure(size + 5);
      this.text(this.margin, this.y - size, size, false, color, ln);
      this.y -= size + 5;
    }
    this.y -= 6;
  }

  grid(items: { label: string; value: string }[]) {
    const cellW = (this.contentW - 12) / 2;
    for (let i = 0; i < items.length; i += 2) {
      this.ensure(58);
      const top = this.y;
      for (let j = 0; j < 2 && i + j < items.length; j++) {
        const cellX = this.margin + j * (cellW + 12);
        this.strokeRect(cellX, top - 46, cellW, 46, BORDER);
        this.text(cellX + 12, top - 19, 9, false, GRAY, items[i + j].label);
        this.text(cellX + 12, top - 35, 13, true, INK, items[i + j].value);
      }
      this.y = top - 46 - 12;
    }
  }

  chips(items: string[]) {
    const chipH = 20;
    this.ensure(chipH + 8);
    let top = this.y;
    let cx = this.margin;
    for (const chip of items) {
      const w = textWidth(chip, 10) + 18;
      if (cx + w > this.margin + this.contentW && cx > this.margin) {
        this.y -= chipH + 7;
        this.ensure(chipH + 7);
        top = this.y;
        cx = this.margin;
      }
      this.strokeRect(cx, top - chipH, w, chipH, BORDER);
      this.text(cx + 9, top - 14, 10, false, DARK, chip);
      cx += w + 8;
    }
    this.y = top - chipH - 14;
  }

  table(rows: { label: string; value: string }[]) {
    for (const row of rows) {
      this.ensure(26);
      const top = this.y;
      this.text(this.margin, top - 16, 11, false, DARK, row.label);
      const vx = this.margin + this.contentW - textWidth(row.value, 11);
      this.text(vx, top - 16, 11, true, INK, row.value);
      this.line(this.margin, top - 24, this.margin + this.contentW, top - 24, BORDER, 0.5);
      this.y = top - 26;
    }
    this.y -= 4;
  }

  footer(date: string) {
    const yFoot = this.margin + 22;
    this.line(this.margin, yFoot, this.margin + this.contentW, yFoot, BORDER, 0.5);
    this.text(this.margin, yFoot - 13, 9, false, GRAY, `Generated ${date}`);
    const right = `${siteConfig.name} · ${siteConfig.url}`;
    this.text(this.margin + this.contentW - textWidth(right, 9), yFoot - 13, 9, false, GRAY, right);
  }

  // --- assembly -------------------------------------------------------------
  build(): Blob {
    this.pages.push(this.cur);
    const bodies: string[] = [];
    bodies[1] = "<< /Type /Catalog /Pages 2 0 R >>";
    // Pages kids assigned below.
    bodies[3] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>";
    bodies[4] =
      "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>";

    const kids: number[] = [];
    this.pages.forEach((content, k) => {
      const contentNum = 5 + 2 * k;
      const pageNum = 6 + 2 * k;
      bodies[contentNum] = `<< /Length ${content.length} >>\nstream\n${content}\nendstream`;
      bodies[pageNum] =
        `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${fmt(this.W)} ${fmt(this.H)}] ` +
        `/Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${contentNum} 0 R >>`;
      kids.push(pageNum);
    });
    bodies[2] = `<< /Type /Pages /Kids [${kids.map((n) => `${n} 0 R`).join(" ")}] /Count ${kids.length} >>`;

    const count = bodies.length - 1; // bodies is 1-indexed
    let pdf = "%PDF-1.4\n";
    const offsets: number[] = [];
    for (let n = 1; n <= count; n++) {
      offsets[n] = pdf.length;
      pdf += `${n} 0 obj\n${bodies[n]}\nendobj\n`;
    }
    const xrefStart = pdf.length;
    pdf += `xref\n0 ${count + 1}\n0000000000 65535 f \n`;
    for (let n = 1; n <= count; n++) {
      pdf += `${String(offsets[n]).padStart(10, "0")} 00000 n \n`;
    }
    pdf += `trailer\n<< /Size ${count + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;

    return new Blob([pdf], { type: "application/pdf" });
  }
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.endsWith(".pdf") ? filename : `${filename}.pdf`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

const slug = (s: string) =>
  sanitize(s)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "") || "document";

function today(): string {
  return new Date().toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" });
}

// --- public API -------------------------------------------------------------

export interface ProposalData {
  title: string;
  subtitle?: string; // developer or agent line
  location: string;
  priceLabel: string;
  highlights: { label: string; value: string }[];
  description: string;
  amenities?: string[];
  paymentPlan?: { label: string; value: string }[];
}

/** Generate and download a branded property proposal as a real PDF. */
export function downloadProposalPdf(data: ProposalData, filename?: string) {
  const doc = new Pdf();
  const { H, margin } = doc;

  // Header band (gradient) with title, subtitle, location, and price.
  const titleLines = wrap(data.title, 22, doc.contentW).slice(0, 2);
  const titleBaselines: number[] = [];
  let ty = H - 84;
  for (let i = 0; i < titleLines.length; i++) {
    titleBaselines.push(ty);
    ty -= 26;
  }
  ty -= 2;
  let subBaseline: number | null = null;
  if (data.subtitle) {
    subBaseline = ty;
    ty -= 18;
  }
  const locBaseline = ty;
  ty -= 26;
  const priceBaseline = ty;
  const bandH = H - priceBaseline + 24;

  doc.gradientBand(0, H - bandH, doc.W, bandH);
  doc.text(margin, H - 32, 11, true, WHITE, siteConfig.name);
  doc.text(margin, H - 50, 9, false, WHITE, "PROPERTY PROPOSAL");
  titleLines.forEach((ln, i) => doc.text(margin, titleBaselines[i], 22, true, WHITE, ln));
  if (data.subtitle && subBaseline !== null) doc.text(margin, subBaseline, 11, false, WHITE, data.subtitle);
  doc.text(margin, locBaseline, 11, false, WHITE, data.location);
  doc.text(margin, priceBaseline, 22, true, WHITE, data.priceLabel);

  doc.y = H - bandH - 26;

  if (data.highlights?.length) {
    doc.heading("Key details");
    doc.grid(data.highlights);
    doc.y -= 6;
  }
  if (data.description) {
    doc.heading("Overview");
    doc.paragraph(data.description);
    doc.y -= 6;
  }
  if (data.amenities?.length) {
    doc.heading("Amenities");
    doc.chips(data.amenities);
    doc.y -= 6;
  }
  if (data.paymentPlan?.length) {
    doc.heading("Payment plan");
    doc.table(data.paymentPlan);
  }

  doc.footer(today());
  triggerDownload(doc.build(), filename ?? `proposal-${slug(data.title)}.pdf`);
}

export interface DocumentMeta {
  name: string;
  property: string;
  type: string;
  status: string;
  updated: string;
}

/** Generate and download a document (contract/disclosure/report) as a real PDF. */
export function downloadDocumentPdf(meta: DocumentMeta, filename?: string) {
  const doc = new Pdf();
  const { H, margin } = doc;
  const bandH = 132;

  doc.gradientBand(0, H - bandH, doc.W, bandH);
  doc.text(margin, H - 34, 11, true, WHITE, siteConfig.name);
  doc.text(margin, H - 52, 9, false, WHITE, meta.type.toUpperCase());
  doc.text(margin, H - 86, 20, true, WHITE, meta.name.replace(/\.pdf$/i, ""));
  doc.text(margin, H - 108, 11, false, WHITE, meta.property);

  doc.y = H - bandH - 26;

  doc.heading("Document details");
  doc.grid([
    { label: "Type", value: meta.type },
    { label: "Status", value: meta.status },
    { label: "Property", value: meta.property },
    { label: "Last updated", value: meta.updated },
  ]);
  doc.y -= 6;

  doc.heading("Summary");
  doc.paragraph(
    `This document (${meta.name}) is associated with the listing "${meta.property}". ` +
      `It is provided through ${siteConfig.name} for record-keeping and review. ` +
      `Please review all terms carefully and consult a licensed professional before signing. ` +
      `This generated copy reflects the document's current status of "${meta.status}".`
  );

  doc.footer(today());
  triggerDownload(doc.build(), filename ?? `${slug(meta.name.replace(/\.pdf$/i, ""))}.pdf`);
}
