"use client";

import { useState } from "react";
import Link from "next/link";
import { Loader2, MessageSquare, PenLine, Sparkles } from "lucide-react";

import { AiStatusBadge } from "@/components/ai/ai-status-badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ApiError, api, isBackendConfigured } from "@/lib/api";

function errorMessage(err: unknown): string {
  if (err instanceof ApiError) {
    if (err.status === 401) return "Log in first — AI tools need a backend session.";
    if (err.status === 402) return "AI quota reached for this plan.";
    return err.message;
  }
  return "Something went wrong.";
}

function AiBadge({ on }: { on: boolean }) {
  return (
    <span
      className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[11px] font-semibold ${
        on ? "bg-ai/10 text-ai" : "bg-muted text-muted-foreground"
      }`}
    >
      <Sparkles className="h-3 w-3" />
      {on ? "Generated by Claude" : "Heuristic fallback"}
    </span>
  );
}

export default function AiStudioPage() {
  // --- description generator ---
  const [form, setForm] = useState({
    city: "Dubai",
    property_type: "condo",
    listing_type: "sale",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1200,
    amenities: "Pool, Gym, Concierge",
    tone: "luxury",
  });
  const [gen, setGen] = useState<{ headline: string; description: string; ai: boolean } | null>(null);
  const [genLoading, setGenLoading] = useState(false);
  const [genError, setGenError] = useState<string | null>(null);

  // --- assistant ---
  const [question, setQuestion] = useState("What does a 60/40 off-plan payment plan mean for a buyer?");
  const [answer, setAnswer] = useState<{ text: string; ai: boolean } | null>(null);
  const [askLoading, setAskLoading] = useState(false);
  const [askError, setAskError] = useState<string | null>(null);

  const runGenerate = async () => {
    setGenError(null);
    setGenLoading(true);
    try {
      const res = await api.generateDescription({
        city: form.city,
        property_type: form.property_type,
        listing_type: form.listing_type,
        bedrooms: Number(form.bedrooms),
        bathrooms: Number(form.bathrooms),
        sqft: Number(form.sqft),
        amenities: form.amenities.split(",").map((a) => a.trim()).filter(Boolean),
        tone: form.tone,
      });
      setGen({ headline: res.headline, description: res.description, ai: res.ai_generated });
    } catch (err) {
      setGenError(errorMessage(err));
    } finally {
      setGenLoading(false);
    }
  };

  const runAsk = async () => {
    setAskError(null);
    setAskLoading(true);
    try {
      const res = await api.assistant(question);
      setAnswer({ text: res.answer, ai: res.ai_generated });
    } catch (err) {
      setAskError(errorMessage(err));
    } finally {
      setAskLoading(false);
    }
  };

  const set = (k: keyof typeof form) => (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) =>
    setForm((f) => ({ ...f, [k]: e.target.value }));

  return (
    <div className="relative">
      <div className="pointer-events-none absolute inset-x-0 top-0 -z-10 h-[340px] bg-mesh-gradient" />
      <div className="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">
              AI <span className="text-gradient">Studio</span>
            </h1>
            <p className="mt-2 text-muted-foreground">
              Live Claude-powered tools, talking to your backend in real time.
            </p>
          </div>
          <AiStatusBadge />
        </div>

        {!isBackendConfigured() && (
          <div className="mt-6 rounded-2xl border bg-warning/10 p-4 text-sm">
            <p className="font-semibold">Backend not connected</p>
            <p className="mt-1 text-muted-foreground">
              Set <code>NEXT_PUBLIC_API_BASE_URL=http://localhost:8000</code> in <code>.env.local</code>,
              start the backend, then refresh. (Log in via the backend to use the tools.)
            </p>
          </div>
        )}

        <div className="mt-8 grid gap-6 lg:grid-cols-2">
          {/* Description generator */}
          <section className="rounded-3xl border bg-card p-6 shadow-card">
            <div className="flex items-center gap-2">
              <span className="inline-flex h-9 w-9 items-center justify-center rounded-xl bg-primary/10 text-primary">
                <PenLine className="h-4 w-4" />
              </span>
              <h2 className="text-lg font-semibold">AI Listing Copywriter</h2>
            </div>
            <div className="mt-4 grid grid-cols-2 gap-3">
              <Input value={form.city} onChange={set("city")} placeholder="City" />
              <select value={form.property_type} onChange={set("property_type")} className="h-11 rounded-lg border border-input bg-background px-3 text-sm">
                {["house", "condo", "apartment", "townhouse", "land"].map((t) => (
                  <option key={t} value={t}>{t}</option>
                ))}
              </select>
              <Input type="number" value={form.bedrooms} onChange={set("bedrooms")} placeholder="Beds" />
              <Input type="number" value={form.bathrooms} onChange={set("bathrooms")} placeholder="Baths" />
              <Input type="number" value={form.sqft} onChange={set("sqft")} placeholder="Sqft" />
              <select value={form.tone} onChange={set("tone")} className="h-11 rounded-lg border border-input bg-background px-3 text-sm">
                {["professional", "luxury", "friendly"].map((t) => (
                  <option key={t} value={t}>{t} tone</option>
                ))}
              </select>
              <Input className="col-span-2" value={form.amenities} onChange={set("amenities")} placeholder="Amenities (comma separated)" />
            </div>
            <Button variant="ai" className="mt-4 w-full" onClick={runGenerate} disabled={genLoading}>
              {genLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
              Generate description
            </Button>
            {genError && <p className="mt-3 text-sm text-destructive">{genError}</p>}
            {genError?.startsWith("Log in") && (
              <Link href="/auth/login" className="mt-1 inline-block text-sm font-medium text-primary hover:underline">
                Go to login →
              </Link>
            )}
            {gen && (
              <div className="mt-4 rounded-2xl border bg-muted/30 p-4">
                <div className="mb-2"><AiBadge on={gen.ai} /></div>
                <p className="font-semibold">{gen.headline}</p>
                <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{gen.description}</p>
              </div>
            )}
          </section>

          {/* Assistant */}
          <section className="rounded-3xl border bg-card p-6 shadow-card">
            <div className="flex items-center gap-2">
              <span className="inline-flex h-9 w-9 items-center justify-center rounded-xl bg-ai/10 text-ai">
                <MessageSquare className="h-4 w-4" />
              </span>
              <h2 className="text-lg font-semibold">AI Property Assistant</h2>
            </div>
            <textarea
              value={question}
              onChange={(e) => setQuestion(e.target.value)}
              rows={4}
              className="mt-4 w-full rounded-lg border border-input bg-background p-3 text-sm"
              placeholder="Ask anything about real estate, off-plan, financing..."
            />
            <Button className="mt-3 w-full" onClick={runAsk} disabled={askLoading || !question.trim()}>
              {askLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : <MessageSquare className="h-4 w-4" />}
              Ask the assistant
            </Button>
            {askError && <p className="mt-3 text-sm text-destructive">{askError}</p>}
            {askError?.startsWith("Log in") && (
              <Link href="/auth/login" className="mt-1 inline-block text-sm font-medium text-primary hover:underline">
                Go to login →
              </Link>
            )}
            {answer && (
              <div className="mt-4 rounded-2xl border bg-muted/30 p-4">
                <div className="mb-2"><AiBadge on={answer.ai} /></div>
                <p className="whitespace-pre-wrap text-sm leading-relaxed">{answer.text}</p>
              </div>
            )}
          </section>
        </div>

        <p className="mt-6 text-center text-xs text-muted-foreground">
          The <strong>“Generated by Claude”</strong> badge confirms real AI; “Heuristic fallback” means no API key is set.
        </p>
      </div>
    </div>
  );
}
